theme: minima
# theme: minima
# remote_theme: pages-themes/merlot@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
title: A story a day keeps Boring Fairy away.
author: AMP
description: It's just a place to record my journey of cultivating critical taste and enhancing literary expression.
show_downloads: true
google_analytics: G-ELNLJR6XRV
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - index.md
minima:
  # skin: classic
  skin: solarized

defaults:
-
  scope:
    path: ""
  values:
      layout: home
      title: A story a day keeps Boring Fairy away.
      author: AMP
      description: >
        It's just a place to record my journey of cultivating critical taste and enhancing literary expression.

-
  scope:
    path: "_posts/*"
  values:
    layout: default
    # page_excerpts: true
